#!/usr/bin/env python3
"""
Generate the ygg_pf encoding test vectors required by spec section 54.

    python3 tools/py_scripts/ygg_pf_vectors.py > data/ygg_pf_vectors.json

The Elixir test suite (backend/test/ygg_pf/codec_vectors_test.exs) reads this file
and asserts byte-for-byte equality. It is the contract between the reference
implementation and the Elixir port.
"""

import json
import sys
import ipaddress

sys.path.insert(0, __file__.rsplit("/", 1)[0])

from ygg_pf_ref import (  # noqa: E402
    AFFIX_BITS, CHECKSUM_BITS, CURSOR_THRESHOLD, EPOCH_SECONDS, N_PARTS,
    PAINTER_BITS, PART_BITS, PREFIX_BITS, YGG_PF_PORT, YID_BYTES,
    PREFIX_LABEL, FIXED_PREFIX_LABEL,
    bit_reverse_per_byte, build_affix, build_yid, derive_fixed_prefix,
    derive_prefix, encode_yaddr, painter_address, split_parts, xor8,
)

H = lambda b: b.hex()  # noqa: E731


def addr_for_key(key: bytes) -> str:
    """Ygg.Address.addr_for_key/1 - used only to produce realistic test addresses."""
    inv = bytes(b ^ 0xFF for b in key)
    bits = "".join(f"{b:08b}" for b in inv)
    ones = 0
    for c in bits:
        if c == "1":
            ones += 1
        else:
            break
    rest = bits[ones + 1:]
    whole = (len(rest) // 8) * 8
    body = rest[:whole]
    bb = bytes(int(body[i:i + 8], 2) for i in range(0, len(body), 8))
    return ipaddress.IPv6Address(bytes([0x02, ones & 0xFF]) + bb[:14].ljust(14, b"\0")).compressed


# Spec section 55: multiple addresses, ports, epochs, cursor values + boundary cases.
ADDRESSES = [
    # the node's own recorded identity - data/ygg/ygg_address.txt
    "202:3eb:bc02:2e59:6617:5771:1ee0:fa2e",
    # derived from deterministic keys, so they are real Ygg addresses
    addr_for_key(bytes(range(32))),
    addr_for_key(b"\x00" * 32),
    addr_for_key(b"\xff" * 32),
    addr_for_key(bytes([0xAA] * 32)),
    # boundary forms
    "200::",
    "203:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
]

PORTS = [YGG_PF_PORT, 0, 1, 1337, 65535]
EPOCHS = [0, 1, 29_000_000, 2 ** 32 - 1, 2 ** 40]
CURSORS = [0, 1, 8, 9, 255]


def main() -> None:
    doc = {
        "_comment": (
            "ygg_pf SDP encoding vectors. Generated by tools/py_scripts/ygg_pf_vectors.py "
            "from the reference implementation in tools/py_scripts/ygg_pf_ref.py. "
            "Do not hand-edit."
        ),
        "constants": {
            "painter_bits": PAINTER_BITS,
            "n_parts": N_PARTS,
            "part_bits": PART_BITS,
            "checksum_bits": CHECKSUM_BITS,
            "affix_bits": AFFIX_BITS,
            "prefix_bits": PREFIX_BITS,
            "yid_bytes": YID_BYTES,
            "epoch_seconds": EPOCH_SECONDS,
            "cursor_threshold": CURSOR_THRESHOLD,
            "ygg_pf_port": YGG_PF_PORT,
            "hash": "sha256",
            "prefix_label": PREFIX_LABEL,
            "fixed_prefix_label": FIXED_PREFIX_LABEL,
            "epoch_encoding": "uint64 big-endian, appended as raw bytes",
            "truncation": "leading (most significant) 80 bits of the digest",
            "bit_reversal": "reverse bits within each byte; byte order preserved",
            "checksum": "8-bit XOR fold over the post-bit-reversal 9 bytes",
            "split_order": "part 0 = most significant 72 bits, big-endian",
            "affix_order": "reversed_part (72b) then checksum (8b)",
        },

        # section 54: painter address -> 144-bit representation
        "painter_address": [
            {"yaddr": a, "port": p, "painter_hex": H(painter_address(a, p))}
            for a in ADDRESSES for p in PORTS
        ],

        # section 54: 144-bit -> 72-bit part A / part B
        "split": [
            {
                "painter_hex": H(painter_address(a, YGG_PF_PORT)),
                "part_a_hex": H(split_parts(painter_address(a, YGG_PF_PORT))[0]),
                "part_b_hex": H(split_parts(painter_address(a, YGG_PF_PORT))[1]),
            }
            for a in ADDRESSES
        ],

        # section 54: 72-bit part -> bit-reversed representation
        "bit_reversal": [
            {"part_hex": H(part), "reversed_hex": H(bit_reverse_per_byte(part))}
            for a in ADDRESSES
            for part in split_parts(painter_address(a, YGG_PF_PORT))
        ] + [
            {"part_hex": H(v), "reversed_hex": H(bit_reverse_per_byte(v))}
            for v in (b"\x00" * 9, b"\xff" * 9, b"\x01" * 9, b"\x80" * 9,
                      bytes(range(9)))
        ],

        # section 54: part -> 8-bit checksum
        "checksum": [
            {
                "reversed_part_hex": H(bit_reverse_per_byte(part)),
                "checksum": xor8(bit_reverse_per_byte(part)),
            }
            for a in ADDRESSES
            for part in split_parts(painter_address(a, YGG_PF_PORT))
        ],

        # section 54: part -> affix
        "affix": [
            {"part_hex": H(part), "affix_hex": H(build_affix(part))}
            for a in ADDRESSES
            for part in split_parts(painter_address(a, YGG_PF_PORT))
        ],

        # section 54: epoch + part + cursor -> 80-bit prefix
        "prefix": [
            {"part_index": n, "cursor": r, "epoch": e,
             "prefix_hex": H(derive_prefix(n, r, e))}
            for n in range(N_PARTS) for r in CURSORS for e in EPOCHS
        ],

        "fixed_prefix": [
            {"part_index": n, "prefix_hex": H(derive_fixed_prefix(n))}
            for n in range(N_PARTS)
        ],

        # section 54: 80-bit prefix + 80-bit affix -> 20-byte yid
        "yid": [
            {
                "yaddr": a, "port": p, "cursor": r, "epoch": e,
                "yid_0_hex": H(encode_yaddr(a, r, e, p)[0]),
                "yid_1_hex": H(encode_yaddr(a, r, e, p)[1]),
            }
            for a in ADDRESSES for p in (YGG_PF_PORT, 0, 65535)
            for r in (0, 1, 9) for e in (0, 29_000_000)
        ],

        # explicit composition check
        "compose": [
            {
                "prefix_hex": H(derive_prefix(0, 0, 29_000_000)),
                "affix_hex": H(build_affix(split_parts(painter_address(ADDRESSES[0]))[0])),
                "yid_hex": H(build_yid(
                    derive_prefix(0, 0, 29_000_000),
                    build_affix(split_parts(painter_address(ADDRESSES[0]))[0]))),
            }
        ],
    }
    json.dump(doc, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
