defmodule YggPF.CodecVectorsTest do
  @moduledoc """
  Binds the Elixir codec to the reference implementation (spec sections 54, 55).

  Vectors are generated by `tools/py_scripts/ygg_pf_vectors.py` from
  `tools/py_scripts/ygg_pf_ref.py` into `data/ygg_pf_vectors.json`. If this test
  fails, either the Elixir port drifted or the reference changed - the two must
  never disagree, because the vectors are the normative definition of the wire
  format.
  """

  use ExUnit.Case, async: true

  alias YggPF.{Codec, Const}

  @vectors_path Path.expand("../../../data/ygg_pf_vectors.json", __DIR__)

  setup_all do
    case File.read(@vectors_path) do
      {:ok, body} ->
        {:ok, vectors: Jason.decode!(body)}

      {:error, reason} ->
        flunk("""
        Cannot read #{@vectors_path}: #{inspect(reason)}

        Regenerate with:
            python3 tools/py_scripts/ygg_pf_vectors.py > data/ygg_pf_vectors.json
        """)
    end
  end

  defp hex(s), do: Base.decode16!(s, case: :lower)

  describe "constants agree with the reference" do
    test "geometry", %{vectors: v} do
      c = v["constants"]
      assert c["painter_bits"] == Const.painter_bits()
      assert c["n_parts"] == Const.n_parts()
      assert c["part_bits"] == Const.part_bits()
      assert c["checksum_bits"] == Const.checksum_bits()
      assert c["affix_bits"] == Const.affix_bits()
      assert c["prefix_bits"] == Const.prefix_bits()
      assert c["yid_bytes"] == Const.yid_bytes()
      assert c["epoch_seconds"] == Const.epoch_seconds()
      assert c["cursor_threshold"] == Const.cursor_threshold()
      assert c["ygg_pf_port"] == Const.ygg_pf_port()
    end

    test "labels", %{vectors: v} do
      assert v["constants"]["prefix_label"] ==
               "fswarm/v1/bootstrap_prefix/part_{n}_and_cursor_{r}"

      assert Const.prefix_label(0, 0) == "fswarm/v1/bootstrap_prefix/part_0_and_cursor_0"
      assert Const.prefix_label(1, 9) == "fswarm/v1/bootstrap_prefix/part_1_and_cursor_9"
      assert Const.fixed_prefix_label(1) == "fswarm/v1/bootstrap_prefix/fixed/part_1"
    end
  end

  test "painter address vectors", %{vectors: v} do
    for %{"yaddr" => a, "port" => p, "painter_hex" => want} <- v["painter_address"] do
      {:ok, ip} = :inet.parse_ipv6_address(String.to_charlist(a))
      assert Codec.painter_address(ip, p) == hex(want), "painter mismatch for #{a}:#{p}"
    end
  end

  test "split vectors", %{vectors: v} do
    for %{"painter_hex" => ph, "part_a_hex" => a, "part_b_hex" => b} <- v["split"] do
      assert Codec.split_parts(hex(ph)) == [hex(a), hex(b)]
    end
  end

  test "bit reversal vectors", %{vectors: v} do
    for %{"part_hex" => p, "reversed_hex" => r} <- v["bit_reversal"] do
      assert Codec.reverse_bits(hex(p)) == hex(r)
      # involution
      assert Codec.reverse_bits(hex(r)) == hex(p)
    end
  end

  test "checksum vectors", %{vectors: v} do
    for %{"reversed_part_hex" => rp, "checksum" => c} <- v["checksum"] do
      assert Codec.xor8(hex(rp)) == c
    end
  end

  test "affix vectors", %{vectors: v} do
    for %{"part_hex" => p, "affix_hex" => a} <- v["affix"] do
      assert Codec.build_affix(hex(p)) == hex(a)
      assert Codec.parse_affix(hex(a)) == {:ok, hex(p)}
    end
  end

  test "prefix vectors", %{vectors: v} do
    for %{"part_index" => n, "cursor" => r, "epoch" => e, "prefix_hex" => want} <- v["prefix"] do
      assert Codec.derive_prefix(n, r, e) == hex(want),
             "prefix mismatch for part=#{n} cursor=#{r} epoch=#{e}"
    end
  end

  test "fixed prefix vectors", %{vectors: v} do
    for %{"part_index" => n, "prefix_hex" => want} <- v["fixed_prefix"] do
      assert Codec.derive_fixed_prefix(n) == hex(want)
    end
  end

  test "yid vectors", %{vectors: v} do
    for %{"yaddr" => a, "port" => p, "cursor" => r, "epoch" => e,
          "yid_0_hex" => y0, "yid_1_hex" => y1} <- v["yid"] do
      {:ok, ip} = :inet.parse_ipv6_address(String.to_charlist(a))
      assert Codec.encode({ip, p}, r, e) == [hex(y0), hex(y1)],
             "yid mismatch for #{a}:#{p} cursor=#{r} epoch=#{e}"

      # and the inverse
      assert Codec.decode([hex(y0), hex(y1)], r, e) == {:ok, {ip, p}}
    end
  end

  test "composition vector", %{vectors: v} do
    for %{"prefix_hex" => p, "affix_hex" => a, "yid_hex" => y} <- v["compose"] do
      assert Codec.build_yid(hex(p), hex(a)) == hex(y)
      assert Codec.split_yid(hex(y)) == {hex(p), hex(a)}
    end
  end
end
